GET http://localhost:2000/check HTTP/1.1


###

GET http://localhost:2000/check/6459400ea832049470808047 HTTP/1.1

###

POST http://localhost:2000/check/ HTTP/1.1
Content-Type: application/json

{   
    "descripcion": "Cff",
    "tipo": "hipismo"

    
}

###

PUT http://localhost:2000/nota/643eda672eb577c72df7bcf4 HTTP/1.1
Content-Type: application/json

{   
    "descripcion": "Curso chevere Mern"
   
}
###

DELETE http://localhost:2000/check/6459400ea832049470808047 HTTP/1.1