GET http://localhost:2000/cronograma HTTP/1.1


###

GET http://localhost:2000/cronograma/64550f3a160accb6fab8655b HTTP/1.1

###

POST http://localhost:2000/cronograma/ HTTP/1.1
Content-Type: application/json

{   
    "descripcion": "COPPA DEL REY GRAN FINAL",
    "fechaentrega": "5/4/2023",
    "fechainicio": "5/6/2023",
    "fechafin": "5/7/2023"

    
}

###

PUT http://localhost:2000/nota/643eda672eb577c72df7bcf4 HTTP/1.1
Content-Type: application/json

{   
    "descripcion": "Curso chevere Mern"
   
}
###

DELETE http://localhost:2000/cronograma/64550e01a5a7c9950bc51919 HTTP/1.1