GET http://localhost:2000/nota HTTP/1.1


###

GET http://localhost:2000/nota/643edb0e316e4d7a6be96fb2 HTTP/1.1

###

POST http://localhost:2000/nota/ HTTP/1.1
Content-Type: application/json

{   
    "descripcion": "Curso Mern as"
    
}

###

PUT http://localhost:2000/nota/643eda672eb577c72df7bcf4 HTTP/1.1
Content-Type: application/json

{   
    "descripcion": "Curso chevere Mern"
   
}
###

DELETE http://localhost:2000/nota/643edb16316e4d7a6be96fb6 HTTP/1.1